#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  4 08:13:01 2017

@author: souravi
"""

lst=[]
dic_day={}
max_v=0
max_k=0
file=open("/Users/souravi/Documents/Python/romeo.txt")
'''1'''
for line in file:
    line=line.rstrip()
    lst=line.split()
    if lst[0]=='From':
        if lst[1] in dic_day:
            
            dic_day[lst[1]]+=1
        else:
            dic_day[lst[1]]=1
print(max(dic_day, key=dic_day.get),dic_day[max(dic_day, key=dic_day.get)])

'''method 2 '''

v=list(dic_day.values())
k=list(dic_day.keys())

#print(k[index(max(v))])

print(k[v.index(max(v))],max(v))
